#!/bin/sh

#export DISPLAY=:0

# Minimum total (ram + swap) percentage before message is displayed

# daemon --name="yourservicename" --output=log.txt sh yourscript.sh

# daemon --name="lowMemAlert" sh /home/sebastian/gene42/git/tools/low-mem-alert

# daemon --name="lowMemAlert" --output=/home/ubuntu/clients/niaid/log.txt sh /home/ubuntu/clients/niaid/pt-niaid-1.0/start.sh

THRESHOLD_PERC=80
SLEEP_INTERVAL=30

while :
do

    mem_used=$(free -m | awk '/^Mem/{print $3}')
    mem_total=$(free -m | awk '/^Mem/{print $2}')
    swap_used=$(free -m | awk '/^Swap/{print $3}')
    swap_total=$(free -m | awk '/^Swap/{print $2}')

    mem_total_used=$(expr $mem_used + $swap_used)
    mem_total=$(expr $mem_total + $swap_total)

    mem_total_used_100=$(expr $mem_total_used \* 100)
    mem_usage_perc=$(expr $mem_total_used_100 / $mem_total)

    message="$mem_total_used MB / $mem_total MB [${mem_usage_perc}%]"

    if [ "$mem_usage_perc" -gt "$THRESHOLD_PERC" ]; then
        /usr/bin/notify-send "Memory is running out!" "$message"
    fi

    echo "$message"

     sleep $SLEEP_INTERVAL

done